# Window settings
WINDOW_WIDTH = 1600
WINDOW_HEIGHT = 800
CANVAS_REFRESH_PERIOD_MS = 50

# Display settings
DISPLAY_PHEROMONES = True
DISPLAY_SLIME = True
DISPLAY_SLIME_SIZE = 1
DISPLAY_SLIME_OPACITY = 75
DISPLAY_SLIME_COLOR = {255, 255, 0, DISPLAY_SLIME_OPACITY}
DISPLAY_HIGHLIGHT_PHEROMONE_COLOR = {0, 255, 0, 255}
DISPLAY_INACTIVE_PHEROMONE_COLOR = {255, 0, 255, 255}


def DISPLAY_DEFAULT_PHEROMONE_COLOR(level): return 0, min((1 - level) * 2, 1.0) * level * 255, level * 255


def COLOR_FROM_ARRAY(t): return t[0], t[1], t[2], t[3]


# Grid settings
GRID_WIDTH = 400
GRID_HEIGHT = 200
LOOP_GRID = True

# Pheromones settings
PHEROMONE_MAX_LEVEL = 1000
PHEROMONE_HIGH_LEVEL_DIFFUSION_MULTIPLIER = 0.5
PHEROMONE_LOW_LEVEL_DIFFUSION_MULTIPLIER = 0
PHEROMONE_DIFFUSION_CONSTANT = 5
PHEROMONE_MAX_LEVEL_RESET_VALUE = PHEROMONE_MAX_LEVEL

# Natural pheromones settings
RANDOM_NATURAL_PHEROMONES_COUNT = 0
NATURAL_PHEROMONES_STRENGTH = PHEROMONE_MAX_LEVEL

# Environment settings
SLIME_COUNT = 10000

# Slime general settings
SLIME_SPEED = 0.5

# Slime wall avoidance settings
SLIME_AVOID_WALLS = True
SLIME_WALL_DETECTION_RANGE = 10
SLIME_WALL_TURN_ANGLE = 0.05

# Slime pheromones settings
SLIME_SEEK_PHEROMONES = True
SLIME_SEEK_PHEROMONES_PERIOD = 2
SLIME_PHEROMONE_DETECTION_RANGE = 5
SLIME_PHEROMONE_TURN_ANGLE = 0.5
SLIME_PHEROMONE_LEVEL = 25
SLIME_IGNORE_SELF_PHEROMONE = True

# Slime direction alignment settings
SLIME_ALIGN_DIRECTION = False
SLIME_OTHER_DETECTION_RANGE = SLIME_PHEROMONE_DETECTION_RANGE
SLIME_ALIGN_TURN_ANGLE = 0.1

# Slime random rotation settings
SLIME_RANDOM_ROTATION_CHANCE = 0.1
SLIME_RANDOM_ROTATION_ANGLE = 1

# Slime default direction settings
SLIME_BIAS_DIRECTION = True
SLIME_BIAS_DIRECTION_X = (GRID_WIDTH / 2)
SLIME_BIAS_DIRECTION_Y = (GRID_HEIGHT / 2)
SLIME_BIAS_ROTATION_ANGLE = 0.01

# Parameters settings
PARAMETER_FILE_NAME = "parameters.txt"
PARAMETER_DELIMITER = ' '
PARAMETER_TRUE_VALUES = ["true", "True", "t", "T", "1"]
PARAMETER_FALSE_VALUES = ["false", "False", "f", "F", "0"]
PARAMETER_UPDATE_PERIOD_MS = 250
